post http://127.0.0.1:3000/signup
Content-Type: application/json

{
    "username": "Nikhil",
    "email": "nik@gmail.com",
    "password": "nik12345"
}

###

post http://127.0.0.1:3000/login
Content-Type: application/json

{
    "username": "Nikhil",
    "password": "nik2345"
}

###