post http://127.0.0.1:3000/signup
Content-Type: application/json

{
    "username": "Bhawesh",
    "email": "bhawesh@gmail.com",
    "password": "bhawesh987"
}

###

post http://127.0.0.1:3000/login
Content-Type: application/json

{
    "username": "Bhawesh",
    "password": "bhawesh987"
}

###